#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-dingyue"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2f36b690d1034520aac675f6e672e5de" }
]
